### ISSUE TITLE
Dependencies ergänzen

### ISSUE THREAD

**Issue by chw9022** [chw9022/IIS_Projekt_Bestellung_per_Drohne#4]
Derzeit kann nicht aufgelöst werden:

- import org.apache.camel.converter.jaxb.JaxbDataFormat;
- import javax.jms.ConnectionFactory;
- import org.apache.activemq.ActiveMQConnectionFactory;
- import org.apache.camel.component.jms.JmsComponent;

**Comment by l1x3** [comment]
Dependencies sollten jetzt vollständig sein. Kannst du das prüfen?

**Comment by chw9022** [comment]
Sorry, ich glaub die haben schon gepasst.
Bekomme jetzt nach einem Maven install aber immer folgenden Fehler:
Tests in error: 
  de.thi.iis.Bestellung_per_Drohne.InMemoryH2Test: org/springframework/core/ErrorCoded

**Comment by l1x3** [comment]
Ich vermute das kommt weil du das Prozessmodell zu unserem geändert hast. Das ist ein Test der mit dem Projekt erstellt wurde. Den Test können wir also löschen.

**Comment by chw9022** [comment]
Alles klar...
Leider kann ich derzeit auch nicht deployen... hat trotzdem schon irgendwas mit dem SpringFramework zu tun...

ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.deployment.unit."Bestellung_per_Drohne.war".component."org.springframework.http.server.reactive.ServletServerHttpRequest$RequestAsyncListener".WeldInstantiator: org.jboss.msc.service.StartException in service jboss.deployment.unit."Bestellung_per_Drohne.war".component."org.springframework.http.server.reactive.ServletServerHttpRequest$RequestAsyncListener".WeldInstantiator: Failed to start service

**Comment by l1x3** [comment]
Ich habe jetzt die Tests gelöscht (und Serializable to Orders hinzugefügt). So wie es jetzt ist kann ich builden.

**Comment by chw9022** [comment]
Japp schaut gut aus
.war wird anscheinend garnicht erst erzeugt wenn die Tests fehlschlagen...
